name: Last.fm - Readme
description: Dynamically update your README with Last.fm metrics
author: dxnter
branding:
  color: red
  icon: music
inputs:
  LASTFM_API_KEY:
    description: Your Last.fm API Key
    required: true
  LASTFM_USER:
    description: Last.fm username to fetch metrics for
    required: true
  GH_TOKEN:
    description: GitHub access token with Repo scope
    default: ${{ github.token }}
    required: false
  REPOSITORY:
    description: Your GitHub repository
    default: ${{ github.repository }}
    required: false
  COMMIT_MESSAGE:
    description: Add a commit message of your choice
    default: 'chore: update Last.fm sections'
    required: false
  SHOW_TITLE:
    description: Toggle the title shown above chart sections
    default: 'true'
    required: false
  LOCALE:
    description: Locale used for formatting numbers
    default: en-US
    required: false
  DATE_FORMAT:
    description: Date format used in the User Info section
    default: MM/dd/yyyy
    required: false
runs:
  using: node16
  main: dist/index.js
